### ISSUE TITLE
Responsive Home Page

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#10]
The homepage is not currently responsive. The `Hero.tsx` component should be updated with appropriate tailwind classes to make the page fully responsive. On smaller screens, the <h1> should be stacked on top of the subscribe form.

![CleanShot 2024-02-26 at 20 38 03](https://github.com/jamesqquick/deals-for-devs/assets/5391915/95b2acca-dbf8-42f4-9e4f-f51a6381cb0b)

The responsive version should look like this.

![CleanShot 2024-02-26 at 20 40 02](https://github.com/jamesqquick/deals-for-devs/assets/5391915/68449019-5863-479d-934f-e409d8f074be)

**Comment by elliezub** [comment]
Hey @jamesqquick can you assign me to this issue? :)

**Comment by jamesqquick** [comment]
Done!
