### ISSUE TITLE
[BUG]: Confirmation email formatting - button overlapping text

### ISSUE THREAD

**Issue by elliezub** [Learn-Build-Teach/deals-for-devs#101]
**Describe the bug**
Confirmation email when subscribing is weirdly formatted, the confirm email button overlaps the words. I'm using Gmail & chrome to view the email.

**Screenshots**
![Screenshot 2024-03-30 150046](https://github.com/Learn-Build-Teach/deals-for-devs/assets/112726692/d1f1458b-09c1-4aad-b850-f54445b70e4c)

**Comment by CBID2** [comment]
Do you want to work on this @elliezub?

**Comment by elliezub** [comment]
@CBID2 No, just wanted to add it as an issue.

**Comment by FatumaA** [comment]
Hi @CBID2,
Was checking out this project, would like to fix this 🙂

**Comment by CBID2** [comment]
You’re good to go @FatumaA
