### ISSUE TITLE
Onboarding email still mentions Black Friday Deals[BUG]

### ISSUE THREAD

**Issue by ryandotfurrer** [Learn-Build-Teach/deals-for-devs#105]
**Describe the bug**
I had to re-signup to the platform and was greeted with an onboarding email containing verbiage about Black Friday

**To Reproduce**
1. Go to [Deals for Devs](https://www.dealsfordevs.com/)
2. Create a new account
3. Check your email
4. See issue

**Expected behavior**
Since this is now for year-round deals, there shouldn't explicitly be verbiage pertaining to Black Friday.

**Screenshots**
![Screenshot of email containing Black Friday verbiage](https://github.com/Learn-Build-Teach/deals-for-devs/assets/40150036/4af80441-c965-427b-9b5f-7a4d68e62608)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Arc (Chromium based)
 - Version: Based on Chromium version 123.0.6312.123 (Official Build) (arm64)

**Suggested Solution**
Change the email template

**Comment by jamesqquick** [comment]
Will be addressed after shipping mvp 1!
