### ISSUE TITLE
[FEATURE]: Create `SearchedDealCard.tsx` component in Search Results

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#118]
As a user, I want to view results when performing a search.

**Implementation**
The search results (in the `GlobalSearch.tsx`) should be displayed using a new `SearchedDealCard.tsx`.

![CleanShot 2024-05-21 at 10 18 08](https://github.com/Learn-Build-Teach/deals-for-devs/assets/5391915/021ac53a-10d5-4a4f-ae33-3d6247102e1e)

**Comment by ryandotfurrer** [comment]
I'm happy to take this on. However, the earliest I can start it is Thursday, June 6.
