### ISSUE TITLE
[FEATURE]: Add Disclaimer Page

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#120]
Wording to be figured out, but we will want a page to explain to users how deals are curated. This will also clarify that we try to keep deal information up to date but cannot guarantee details haven't changed without our knowledge.

**Comment by klae32** [comment]
@jamesqquick Is this going to be it's own route?

**Comment by jamesqquick** [comment]
@klae32 My guess is yes. We can link to it from the footer and from indiviual deal paged
