### ISSUE TITLE
Add notification for subscription being processed

### ISSUE THREAD

**Issue by chris-nowicki** [Learn-Build-Teach/deals-for-devs#14]
Animate the airplane to be a rotating circle while the subscription is being processed.  This will indicate to the subscriber that something is happening.  Otherwise there is a short delay.

![CleanShot 2024-03-01 at 11 24 27](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/0d18a41c-80f4-4605-9b01-b515642d8a08)

**Comment by jamesqquick** [comment]
This can use the rotate class from Tailwind - https://tailwindcss.com/docs/rotate

Example here using the `useFormStatus()` hook with Server Actions to detect the `pending` state of the form. https://github.com/vercel/next.js/blob/canary/examples/next-forms/app/add-form.tsx

When the form is `pending` it should add the rotate class to the icon.
