### ISSUE TITLE
[BUG]: Don't Allow End Dates Before Start Date

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#177]
**Is your feature request related to a problem? Please describe.**
As a user, I should not be allowed to select an end date for a deal before the start date.

**Describe the solution you'd like**
Add custom validation to the date input for coupon details to prevent end dates before the start dates

**Describe the benefits of your solution**
Better UX for creating valid deal data

**Comment by 24HourDeveloper** [comment]
I like to take this bug.
