### ISSUE TITLE
Move Sentry DSN to an Environment Variable

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#18]
The `dsn` property in multiple locations (`sentry.server.config.ts`, `sentry.edge.config.ts`, and `sentry.client.config.ts`) is hard-coded to James's personal Sentry account. This property should be moved to an environment variables called `NEXT_PUBLIC_SENTRY_DSN` and referenced in the config files as `process.env.NEXT_PUBLIC_SENTRY_DSN`.

The `.env.example` file should be updated to include a reference to this new variable as well.

**Comment by klae32** [comment]
@jamesqquick I was trying to move the card on the Kanban but it would not allow me to do so. This one is mainly done but stuck in `No Status`
