### ISSUE TITLE
Zod Validation for .env Variables

### ISSUE THREAD

**Issue by chris-nowicki** [Learn-Build-Teach/deals-for-devs#3]
Add type safe validations for .env variables.

**Comment by jamesqquick** [comment]
Example - https://catalins.tech/validate-environment-variables-with-zod/

**Comment by chris-nowicki** [comment]
@klae32 Thanks so much for trying to tackle this.  If possible look at this option: https://x.com/mattpocockuk/status/1760991147793449396?s=46&t=mMZarbrAtPqA1n6AYv51ug

@jamesqquick sent that over to me today and looks like a nice elegant solution.

Thanks!

**Comment by klae32** [comment]
@chris-nowicki I just finished up something similar to that but more like the article from above. Let me know if you want it more concise like the twitter/X post or the way I have it. I am good with either. Just want to make sure we get it dialed in before Merging.
