### ISSUE TITLE
Change hard-coded class values to built-in tailwind classes

### ISSUE THREAD

**Issue by elliezub** [Learn-Build-Teach/deals-for-devs#34]
Throughout the project there are hard-coded class values for example, `md:mb-[153px]` in Nav.tsx, Let's update them to built-in class values like `md:mb-36` or create custom classes.

![navtsx](https://github.com/Learn-Build-Teach/deals-for-devs/assets/112726692/fc2a1dd1-f6b2-4c33-b7e7-95544cf7362e)

**Comment by CBID2** [comment]
Hey @elliezub. How are you doing with this issue?

**Comment by elliezub** [comment]
@CBID2 Still working on it, had the flu the last few days and am finally feeling a bit better now.
