### ISSUE TITLE
Create a xata table for Categories

### ISSUE THREAD

**Issue by chris-nowicki** [Learn-Build-Teach/deals-for-devs#5]
Database table in Xata is needed to add deal categories that can be looped through in the application in places category names are being used.

**Comment by brwmaster** [comment]
@chris-nowicki just to be sure. Do we have any documentation about the fields we want to add inside this table? Or is creating the table enough?

**Comment by jamesqquick** [comment]
@brwmaster we will need to include all the values that are defined in the `Category` enum in the `Types.ts` file. Then, we'll need to replace that enum with the list of values retrieved from the db. I can handle the DB part if you work on the code part to reference those options. Does that make sense?

**Comment by brwmaster** [comment]
@jamesqquick sure thing. Will have a look at it tonight

**Comment by jamesqquick** [comment]
@brwmaster I thought about this some more last night, and i actually think I might back away from it. I think it might make sense to keep it in the enum for now. Sorry for the tease! lol

**Comment by brwmaster** [comment]
@jamesqquick Haha no problem. These things happen. Then this issue can be closed I guess?
