### ISSUE TITLE
[FEATURE]: Create multi-step share a deal form

### ISSUE THREAD

**Issue by chris-nowicki** [Learn-Build-Teach/deals-for-devs#74]
**Is your feature request related to a problem? Please describe.**
We need the share a deal form to be created using figma design.  @jamesqquick  and/or @chris-nowicki can get you a link to the figma file.

**Describe the solution you'd like**

![Share a deal - Step one](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/73d5f3e3-4334-4695-b203-5714180efd28)

![Share a deal - Step two](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/ff48ef3b-a1d3-4047-bcfe-1d6715559dde)

![Share a deal - Step three](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/b2c332ea-7573-45de-9aa2-b5110710018d)

![Share a deal - Step four](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/867d9abd-8113-48fa-b2e0-e248cb590310)

![Share a deal - Success](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/90014c74-03bf-4747-920b-f2a221fb65ed)

**Comment by CBID2** [comment]
Hey @chris-nowicki. Do you want to switch issues with me? I’m currently assigned to
