### ISSUE TITLE
[FEATURE]: Add feature deals section on landing page

### ISSUE THREAD

**Issue by chris-nowicki** [Learn-Build-Teach/deals-for-devs#75]
Add a featured deals section to the landing page between the first separator below the header and the never miss a deal section.  @jamesqquick  and/or @chris-nowicki  can provide the Figma file.

Features include:
- Should show top 6 featured deals
- featured deals will have a `featured` boolean property set to true
- should use the existing `FeaturedDeals.tsx` component
- should update h2 to say "Hottest Deals"
- should add a link to the right of the h2 that says "view all deals" that links to `/deals`

- Should NOT have a list of categories to filter by (this will come in the future)	
- Should not focus on design of deal cards (this will be another issue)

**Describe the solution you'd like**

![CleanShot 2024-03-18 at 22 45 12](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/bd7b974b-f7d1-49ef-b9f0-f064d6b06a5c)

**Comment by CBID2** [comment]
I'll try this @chris-nowicki
