### ISSUE TITLE
[FEATURE]: Update Search Modal

### ISSUE THREAD

**Issue by chris-nowicki** [Learn-Build-Teach/deals-for-devs#77]
**Is your feature request related to a problem? Please describe.**
The design of how the search modal displays deals needs to be updated.  @jamesqquick or @chris-nowicki can provide the figma file.

There are a few states: 

1. _Empty_ - when the modal first opens
2. _No Results Found_ - when there are no search results
3. _Loading_ - when the deals are loading.  Should show a skeleton of the deal
4. _List of results_ - shows list of deals based on search

![Empty state](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/314efed0-9352-4c31-8788-33e84fa7bcb9)

![No results found](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/1c2d6cbf-9801-47e8-95d6-83a7d7317c7e)

![Loading state](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/1c1d8a01-f252-4e64-8599-e2fe65b2fdb3)

![List of results](https://github.com/Learn-Build-Teach/deals-for-devs/assets/102450568/b6d2afe4-7651-4b38-aa04-830ed0d6f9f1)

**Comment by ryandotfurrer** [comment]
I'm happy to take this on @jamesqquick and @chris-nowicki. Provide the Figma file and I can make it happen this weekend.
