### ISSUE TITLE
Move Clerk Provider Only To Admin Dashboard

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#8]
Right now, the Clerk provider is surrounding the entire application which is unnecessary and may cause additional load times. We should move the Clerk provider to only wrap the layout for the admin dashboard so it's not loaded unnecessarily.

**Comment by chris-nowicki** [comment]
@jamesqquick I started to work this but then realized that this is probably tied to #9.  The clerk provider will be in the Admin layout.tsx file and removed from the site layout.tsx file and then having to make a new navbar for admin vs site potentially.

**Comment by ryandotfurrer** [comment]
This was completed with PR #85

**Comment by ryandotfurrer** [comment]
Created PR #106

**Comment by ryandotfurrer** [comment]
Closed with #170
