### ISSUE TITLE
[DOCS]: PR-Template Update

### ISSUE THREAD

**Issue by BryanF1nes** [Learn-Build-Teach/deals-for-devs#83]
## Issue Description 
Please provide a brief summary of the documentation issue you are experiencing or would like to address:

I would like to open up a discussion regarding the current PR-template and propose we improve upon it with some more information.

## Screenshots or Examples (if applicable)
Please include relevant screenshots or examples to help illustrate the problem.

## Proposed Solution (optional)
 If you have a proposed solution for the documentation issue, please provide it here. This can be helpful for speeding up the resolution process.

My proposed solution is to add some additional information whether it be in the form of check boxes to indicate the contributor has followed our standard contributing markdown, as well as some other items that may be useful to maintainers.

**Comment by CBID2** [comment]
Good idea @BryanF1nes
