### ISSUE TITLE
Use Next.js Layouts for Admin Routes

### ISSUE THREAD

**Issue by jamesqquick** [Learn-Build-Teach/deals-for-devs#9]
Right now, we have two pages under the admin dashboard, one for viewing subscribers and one for viewing deals. These aren't treated as true pages. Instead, we are just swapping out the content manually for each one based on state. Instead, we should create two separate route files, one for subscribers, and one for deals. These two route components should have a parent layout that includes the sidebar nav to navigate between the different admin pages.

Next.js layouts - https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts

**Comment by ryandotfurrer** [comment]
Completed with PR #85
